Repository rustymotors/server, pull requests merged in 2022-07, with the labels that each got.

#1161 add connection session model
  packages/mcos-database/src/models/Lobby.test.ts
  packages/mcos-database/src/models/Lobby.ts
  packages/mcos-database/src/models/Player.test.ts
  packages/mcos-database/src/models/Player.ts
  packages/mcos-database/src/models/Session.test.ts
  packages/mcos-database/src/models/Session.ts
Labels: size/L

#1166 add recomended extensions
  .vscode/extensions.json
Labels: size/XS

#1165 Create database microservice
  Makefile
  docker-compose.yml
  packages/mcos-database/src/index.js
  packages/mcos-database/src/server.ts
  packages/mcos-database/src/types.ts
  packages/mcos-shared/src/config/index.js
Labels: size/L

#1183 Create issues for all todo and note comments
  README.md
  docker-compose.elk copy.yml
  docker-compose.elk.yml
  docker-compose.yml
  packages/mcos-gateway/src/sockets.ts
  packages/mcos-lobby/src/index.js
  packages/mcos-login/src/index.js
  packages/mcos-login/src/internal.js
  packages/mcos-persona/src/index.js
  packages/mcos-persona/src/internal.ts
  packages/mcos-shared/src/tcpConnection.ts
  packages/mcos-shared/src/types/index.ts
Labels: size/M

#1186 (JS-0378) Found template literal expression having a non-string type
  packages/mcos-database/src/server.ts
Labels: size/XS

#1189 (JS-0293) Inconsistent array definitions
  packages/mcos-shared/src/tcpConnection.ts
Labels: size/XS

#1190 Add missing return type
  packages/mcos-shared/src/tcpConnection.ts
Labels: size/XS

#1191 Perform typeof checks and enable strictNullChecks
  packages/mcos-shared/src/tcpConnection.ts
  tsconfig.base.json
Labels: size/S

#1194 (JS-R1000) Found multiple import of the same path
  packages/mcos-gateway/src/sockets.ts
Labels: size/S

#1196 Restrict the types allowed in boolean expressions JS-0382
  packages/mcos-gateway/src/sockets.ts
Labels: size/S

#1197 Remove commented out code
  packages/mcos-gateway/src/sockets.ts
  packages/mcos-transactions/src/transactionServer.js
Labels: size/L

#1199 Class methods should utilize `this` JS-0105
  packages/mcos-transactions/src/transactionServer.js
Labels: size/XL

#1200 Migrate config package to enviromental variables
  docker-compose.yml
  docs/server.md
  packages/mcos-database/tsconfig.json
  packages/mcos-gateway/src/web.js
  packages/mcos-gateway/tsconfig.json
  packages/mcos-patch/src/index.js
  packages/mcos-patch/tsconfig.json
  packages/mcos-shard/src/index.js
  packages/mcos-shard/tsconfig.json
  packages/mcos-shared/package.json
  packages/mcos-shared/src/config/index.js
  packages/mcos-shared/src/logger/index.ts
  packages/mcos-shared/src/types/index.ts
Labels: size/L

#1205 Seperate classes and interfactes
  packages/mcos-database/src/index.js
  packages/mcos-gateway/src/connections.ts
  packages/mcos-patch/src/index.js
  packages/mcos-shared/src/structures/BinaryStructure.ts
  packages/mcos-shared/src/structures/TMessageBase.ts
  packages/mcos-shared/src/types/GenericReplyMessage.ts
  packages/mcos-shared/src/types/GenericRequestMessage.ts
  packages/mcos-shared/src/types/MessageNode.ts
  packages/mcos-shared/src/types/NPSMessage.ts
  packages/mcos-shared/src/types/NPSPersonaMapsMessage.ts
  packages/mcos-shared/src/types/NPSUserInfo.ts
  packages/mcos-shared/src/types/NPSUserStatus.ts
  packages/mcos-shared/src/types/NPS_COMMANDS.ts
  packages/mcos-shared/src/types/NPS_LOBBYCLIENT_COMMANDS.ts
  packages/mcos-shared/src/types/NPS_LOBBYSERVER_COMMANDS.ts
  packages/mcos-shared/src/types/NPS_LOBBY_COMMANDS.ts
  packages/mcos-shared/src/types/NPS_LOGINCLIENT_COMMANDS.ts
  packages/mcos-shared/src/types/NPS_LOGIN_COMMANDS.ts
  packages/mcos-shared/src/types/StockCar.ts
  packages/mcos-shared/src/types/StockCarInfoMessage.ts
  packages/mcos-shared/src/types/index.ts
  packages/mcos-shared/src/types/premadeLogin.ts
  packages/mcos-shared/src/types/types.ts
  packages/mcos-transactions/src/internal.ts
  packages/mcos-transactions/src/transactionServer.js
Labels: size/XXL

#1212 Repo visualizer: updated diagram
  diagram.svg
Labels: size/XS

#1214 Add ErrorLens to workspace recomended estensions
  .vscode/extensions.json
Labels: size/XS

#1220 regenerate lockfile
  package-lock.json
Labels: size/XS

#1219 Bring Lobby test coverage to 50%+
  package.json
  packages/mcos-gateway/src/connections.ts
  packages/mcos-gateway/src/nps-packet-manager.ts
  packages/mcos-gateway/src/sockets.ts
  packages/mcos-lobby/src/handlers/encryptedCommand.ts
  packages/mcos-lobby/src/handlers/heartbeat.ts
  packages/mcos-lobby/src/handlers/index.ts
  packages/mcos-lobby/src/handlers/requestConnectGameServer.ts
  packages/mcos-lobby/src/index.ts
  packages/mcos-lobby/src/internal.ts
  packages/mcos-lobby/src/sessionKeys.test.ts
  packages/mcos-lobby/src/types.ts
Labels: size/XXL

#1216 Add Codecov flags for each package
  .github/codecov.yml
  .github/workflows/node.yml
Labels: size/M

#1223 Remove outdated flags
  .github/codecov.yml
Labels: size/XS

#1230 Create semgrep.yml
  .github/workflows/semgrep.yml
Labels: size/S

#1232 Remove remaining imports statements
  packages/mcos-transactions/src/encryption.ts
  packages/mcos-types/encryption.d.ts
Labels: size/S

#1233 Add /admin/connections/resetAllQueueState handler back
  .github/deadpendency.yaml
  package-lock.json
  package.json
  packages/mcos-gateway/src/adminServer.test.ts
  packages/mcos-gateway/src/adminServer.ts
  packages/mcos-gateway/src/web.ts
  packages/mcos-gateway/test/adminServer.test.ts
Labels: size/L

#1235 Disable *-shared flags
  .github/codecov.yml
  .github/workflows/node.yml
Labels: size/S

#1236 Repo visualizer: updated diagram
  diagram.svg
Labels: size/XS

#1237 Fix start command
  package.json
Labels: size/XS

#1238 The login service has duplicated logic between the index.js and internal.js files
  packages/mcos-login/src/index.ts
  packages/mcos-login/src/tcpConnection.ts
Labels: size/XL

#1240 Move configs to package.json
  .c8rc.json
  .eslintignore
  .eslintrc.json
  package.json
Labels: size/S

#1241 Remove duplicated file
  nginx.conf
Labels: size/M

#1242 Remove uses of TCPConnection structures
  packages/mcos-gateway/src/connections.ts
  packages/mcos-gateway/src/tcpConnection.ts
  packages/mcos-persona/src/index.ts
  packages/mcos-transactions/src/index.ts
  packages/mcos-transactions/src/transactionServer.ts
  packages/mcos-types/tcpConnection.d.ts
Labels: size/XXL

#1244 Repo visualizer: updated diagram
  diagram.svg
Labels: size/XS

#1245 Remove instances of errorMessage function
  packages/mcos-gateway/src/BinaryStructure.ts
  packages/mcos-gateway/src/connections.ts
  packages/mcos-gateway/src/sockets.ts
  packages/mcos-lobby/src/encryption.ts
  packages/mcos-lobby/src/index.ts
  packages/mcos-login/src/BinaryStructure.ts
  packages/mcos-login/src/internal.ts
  packages/mcos-transactions/src/BinaryStructure.ts
  packages/mcos-transactions/src/encryption.ts
  packages/mcos-transactions/src/index.ts
  packages/mcos-transactions/src/internal.ts
  packages/mcos-types/BinaryStructure.d.ts
  packages/mcos-types/encryption.d.ts
Labels: size/L

#1246 Refactor logAndThrow out of the codebase
  packages/mcos-gateway/src/sockets.ts
Labels: size/S
