Repository rustymotors/server, pull requests merged in 2024-09, with the labels that each got.

#2112 Refactor docker-compose.yml file
  docker-compose.yml
Labels: size/M

#2113 Update Node.js version to v20.17.0 and fix file paths in node.yml
  .github/workflows/node.yml
  .nvmrc
Labels: size/S

#2115 Refactor channels module and update dependencies
  packages/lobby/src/handlers/channels.ts
  packages/lobby/src/handlers/encryptedCommand.ts
  packages/lobby/src/handlers/handleGetMiniUserList.ts
  packages/lobby/src/handlers/handleSendMiniRiffList.ts
  packages/shared/index.ts
Labels: size/M

#2099 Update node.yml
  .github/workflows/node.yml
Labels: size/XS

#2126 Update log level environment variable in server.ts
  server.ts
Labels: size/XS

#2123 chore(deps): add rusty-motors-chat as a dependency
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  src/chat/index.ts
  src/chat/package.json
  src/chat/tsconfig.json
  src/chat/types.ts
  src/chat/vite.config.ts
Labels: size/L

#2130 Refactor import statements in server.ts
  server.ts
Labels: size/XS

#2151 Remove unused dependencies from package.json and pnpm-lock.yaml
  packages/cli/package.json
  pnpm-lock.yaml
Labels: size/S

#2152 chore(ci): remove standard-version dependency
  package.json
  pnpm-lock.yaml
Labels: size/XL

#2153 chore: :wrench: setup commitlint to enforce conventional commits
  .husky/commit-msg
  commitlint.config.js
  package.json
  pnpm-lock.yaml
Labels: size/XXL

#2155 chore: remove per-module vite config files
  packages/cli/vite.config.ts
  packages/connection/vite.config.ts
  packages/database/vite.config.ts
  packages/gateway/vite.config.ts
  packages/lobby/vite.config.ts
  packages/login/vite.config.ts
  packages/mcots/vite.config.ts
  packages/nps/vite.config.ts
  packages/patch/vite.config.ts
  packages/persona/vite.config.ts
  packages/sessions/vite.config.ts
  packages/shard/vite.config.ts
  packages/shared-packets/vite.config.ts
  packages/shared/vite.config.ts
  src/chat/vite.config.ts
  vite.config.ts
Labels: size/L

#2161 feat: add chat utility functions and tests
  src/chat/assertLength.test.ts
  src/chat/assertLength.ts
  src/chat/timestampToTimeT.test.ts
  src/chat/timestampToTimeT.ts
  src/chat/toHexString.test.ts
  src/chat/toHexString.ts
  src/chat/writeShortBoolean.test.ts
  src/chat/writeShortBoolean.ts
  src/chat/writeZeroTerminatedString.test.ts
  src/chat/writeZeroTerminatedString.ts
Labels: size/L

#2175 refactor: remove unused extension recommendation and add createGameProfile function
  .vscode/extensions.json
  packages/gateway/src/GatewayServer.ts
  packages/gateway/src/index.ts
  packages/lobby/src/handlers/_setMyUserData.ts
  packages/lobby/src/handlers/encryptedCommand.ts
  packages/lobby/src/handlers/requestConnectGameServer.ts
  packages/mcots/src/payloads/LoginCompleteMessage.ts
  packages/nps/gameMessageProcessors/index.ts
  packages/nps/gameMessageProcessors/processGameLogin.ts
  packages/nps/index.ts
  packages/persona/src/getPersonasByPersonaId.ts
  packages/persona/src/handlers/getPersonaInfo.ts
  packages/persona/src/internal.ts
  packages/persona/test/getPersonasByPersonaId.test.ts
  packages/shared/src/interfaces.ts
  src/chat/ChatMessage.ts
  src/chat/InGameEmailMessage.ts
  src/chat/ListInGameEmailsMessage.ts
  src/chat/ListInGameEmailsResponseMessage.ts
  src/chat/inGameEmails.ts
  src/chat/index.ts
Labels: size/XL

#2177 test: :white_check_mark: enable tests for chat module
  pnpm-lock.yaml
  src/chat/package.json
Labels: size/S

#2178 feat: :sparkles: create socket module
  pnpm-lock.yaml
  src/socket/ConnectedSocket.test.ts
  src/socket/ConnectedSocket.ts
  src/socket/index.ts
  src/socket/package.json
  src/socket/tsconfig.json
Labels: size/L

#2180 refactor: :art: migrate to socket module
  package.json
  packages/gateway/src/index.ts
  packages/gateway/src/socketErrorHandler.test.ts
  packages/gateway/src/socketErrorHandler.ts
  packages/shared/index.ts
  packages/shared/src/State.ts
  pnpm-lock.yaml
  src/socket/index.ts
Labels: size/L

#2181 refactor: :art: migrate to socket module, phase 1
  packages/gateway/src/index.ts
  packages/lobby/src/NPS_LOBBYCLIENT_COMMANDS.ts
  packages/lobby/src/NPS_LOBBYSERVER_COMMANDS.ts
  packages/lobby/src/NPS_LOBBY_COMMANDS.ts
  packages/lobby/src/handlers/encryptedCommand.ts
  packages/lobby/src/handlers/heartbeat.js
  packages/lobby/src/handlers/index.js
  packages/lobby/src/internal.ts
  packages/login/src/receiveLoginData.ts
  packages/mcots/src/messageProcessors/index.ts
  packages/mcots/src/messageProcessors/processClientConnect.ts
  packages/mcots/src/messageProcessors/processClientTracking.ts
  packages/mcots/src/messageProcessors/processServerLogin.ts
  packages/mcots/src/messageProcessors/processSetOptions.ts
  packages/mcots/src/messageProcessors/processStockCarInfo.ts
  packages/mcots/src/payloads/ClientConnectMessage.test.ts
  packages/mcots/src/payloads/ClientConnectMessage.ts
  packages/mcots/src/payloads/ClientTrackingMessage.ts
  packages/mcots/src/payloads/LoginMessage.ts
  packages/mcots/src/payloads/SetOptionsMessage.ts
  packages/mcots/src/payloads/StockCar.ts
  packages/persona/src/internal.ts
  packages/shared-packets/index.ts
  packages/shared-packets/src/BasePacket.test.ts
  packages/shared-packets/src/BasePacket.ts
  packages/shared-packets/src/BufferSerializer.test.ts
  packages/shared-packets/src/BufferSerializer.ts
  packages/shared-packets/src/GenericRequestPayload.test.ts
  packages/shared-packets/src/GenericRequestPayload.ts
  packages/shared-packets/src/ServerPacket.test.ts
  packages/shared-packets/src/ServerPacket.ts
  packages/shared-packets/src/interfaces.ts
  packages/shared-packets/src/types.ts
  packages/shared-packets/src/utils.ts
  packages/shared-packets/test/index.test.ts
  packages/shared/src/GameMessage.ts
  packages/shared/src/State.ts
  packages/transactions/src/internal.ts
  src/chat/index.ts
Labels: size/XL
