Repository rustymotors/server, pull requests merged in 2024-02, with the labels that each got.

#1755 Update email address
  package.json
Labels: size/XS

#1757 Update Sentry DSN
  .pnp.cjs
  thebeast/package.json
  thebeast/server.ts
  yarn.lock
Labels: size/M

#1758 Run prettier
  thebeast/lib/nps/messageProcessors/getLobMiniRiffList.ts
  thebeast/lib/nps/messageProcessors/processEncryptedGameCommand.ts
  thebeast/lib/nps/messageStructs/MiniRiffList.ts
  thebeast/lib/nps/messageStructs/MiniUserList.ts
  thebeast/server.ts
Labels: size/M

#1763 Fix runs-on
  .github/workflows/main.yml
Labels: size/XS

#1764 Added Sentry logging for sql
  thebeast/packages/database/src/cache.ts
  thebeast/packages/database/src/models/VehiclePartTree.ts
  thebeast/packages/database/src/services/admin.ts
Labels: size/L

#1766 Fix SQL
  .github/workflows/node.yml
  .gitignore
  .yarnrc.yml
  data/mcouniverse.cnf
  data/mcouniverse.crt
  data/private_key.pem
  data/pub.key
  package-lock.json
  package.json
  thebeast/package.json
Labels: size/L

#1768 Not using build
  .github/workflows/main.yml
Labels: size/XS

#1769 Fix CodeQL badge
  README.md
Labels: size/XS
